"""CommunitySummarizer class."""

import logging

from dbgpt.core import LLMClient
from dbgpt.rag.transformer.llm_summarizer import LLMSummarizer

logger = logging.getLogger(__name__)


class CommunitySummarizer(LLMSummarizer):
    """CommunitySummarizer class."""

    def __init__(self, llm_client: LLMClient, model_name: str):
        """Initialize the CommunitySummaryExtractor."""
        super().__init__(llm_client, model_name, COMMUNITY_SUMMARY_PT_CN)


COMMUNITY_SUMMARY_PT_CN = (
    "## Role\n"
    "You are highly skilled at summarizing knowledge graph information. Based on entity and relation names "
    "and descriptions in a given knowledge graph, you can comprehensively and appropriately summarize "
    "subgraph information without losing key details.\n"
    "\n"
    "## Skills\n"
    "### Skill 1: Entity Recognition\n"
    "- Accurately recognize entity information in the [Entities:] section, including entity names and descriptions.\n"
    "- Common entity formats include:\n"
    "(entity_name)\n"
    "(entity_name:entity_description)\n"
    "(entity_name:entity_property_map)\n"
    "(chunk_id:chunk_content)\n"
    "(catalog_id:catalog_name)\n"
    "(document_id:document_name)\n"
    "\n"
    "### Skill 2: Relation Recognition\n"
    "- Accurately recognize relation information in the [Relationships:] section, including source entity names, "
    "relation names, target entity names, and descriptions; entity names may also be document, catalog, or chunk IDs.\n"
    "- Common relation formats include:\n"
    "(source_entity_name)-[relation_name]->(target_entity_name)\n"
    "(source_entity_name)-[relation_name:relation_description]->(target_entity_name)\n"
    "(source_entity_name)-[relation_name:relation_property_map]->(target_entity_name)\n"
    "(chunk_id)-[Contains]->(entity_name)\n"
    "(catalog_id)-[Contains]->(chunk_entity)\n"
    "(catalog_id)-[Contains]->(sub_catalog_id)\n"
    "(document_id)-[Contains]->(chunk_entity)\n"
    "(document_id)-[Contains]->(catalog_id)\n"
    "\n"
    "### Skill 3: Graph Structure Understanding\n"
    "--Follow these steps to understand the graph structure--\n"
    "1. Correctly link source entity names in relations to entity records.\n"
    "2. Correctly link target entity names in relations to entity records.\n"
    "3. Reconstruct the graph structure from the provided relations."
    "\n"
    "### Skill 4: Knowledge Graph Summarization\n"
    "--Follow these steps to summarize the knowledge graph--\n"
    "1. Identify the theme or topic expressed by the knowledge graph, highlighting key entities and relations."
    "2. Summarize the graph information in accurate, appropriate, concise language without introducing unrelated content."
    "\n"
    "## Constraints\n"
    "- Do not describe your reasoning process; answer the user's question directly without irrelevant content.\n"
    "- Always write in the third person, objectively summarizing the information expressed by the knowledge graph.\n"
    "- If entity or relation descriptions are empty and contribute nothing to the summary, do not generate unrelated content.\n"
    "- If the provided descriptions contradict each other, resolve the conflict and provide a single, coherent description.\n"
    "- Avoid stop words and overly common terms.\n"
    "\n"
    "## Reference Example\n"
    "--The example only helps you understand the input and output format; do not use it in your answer.--\n"
    "Input:\n"
    "```\n"
    "Entities:\n"
    "(Phil Jabber#Founder of Philz Coffee)\n"
    "(Philz Coffee#Coffee brand founded in Berkeley, California)\n"
    "(Jacob Jabber#Son of Phil Jabber)\n"
    "(Multiple locations in the USA#Philz Coffee expansion area)\n"
    "\n"
    "Relationships:\n"
    "(Phil Jabber#Founded#Philz Coffee#Founded in Berkeley, California in 1978)\n"
    "(Philz Coffee#Located in#Berkeley, California#Founding location of Philz Coffee)\n"
    "(Phil Jabber#Has#Jacob Jabber#Son of Phil Jabber)\n"
    "(Jacob Jabber#Serves as#CEO#Became CEO of Philz Coffee in 2005)\n"
    "(Philz Coffee#Expanded to#Multiple locations in the USA#Expansion area of Philz Coffee)\n"
    "```\n"
    "\n"
    "Output:\n"
    "```\n"
    "Philz Coffee is a coffee brand founded by Phil Jabber in 1978 in Berkeley, California. "
    "Phil Jabber's son Jacob Jabber became CEO in 2005 and led the company's expansion to multiple locations in the USA, "
    "further strengthening Philz Coffee's market position as a Berkeley-founded brand.\n"
    "```\n"
    "\n"
    "----\n"
    "\n"
    "Summarize the information expressed by the [KnowledgeGraph] below per the requirements above.\n"
    "\n"
    "[KnowledgeGraph]:\n"
    "{graph}\n"
    "\n"
    "[Summary]:\n"
    "\n"
)

COMMUNITY_SUMMARY_PT_EN = (
    "## Role\n"
    "You are highly skilled in summarizing information from knowledge graphs. "
    "Based on the names and descriptions of entities and relationships in a "
    "given knowledge graph, you can comprehensively and appropriately summarize"
    " the information of the subgraph without losing critical details.\n"
    "\n"
    "## Skills\n"
    "### Skill 1: Entity Recognition\n"
    "- Accurately recognize entity information in the [Entities:] section, "
    "including entity names and descriptions.\n"
    "- The general formats for entity information are:\n"
    "(entity_name)\n"
    "(entity_name: entity_description)\n"
    "(entity_name: entity_property_map)\n"
    "(chunk_id: chunk_content)\n"
    "(catalog_id: catalog_name)\n"
    "(document_id: document_name)\n"
    "\n"
    "### Skill 2: Relationship Recognition\n"
    "- Accurately recognize relationship information in the [Relationships:] "
    "section, including source_entity_name, relationship_name, "
    "target_entity_name, and relationship_description, The entity_name may "
    "also be the document_id, catalog_id, or chunk_id.\n"
    "- The general formats for relationship information are:\n"
    "(source_entity_name)-[relationship_name]->(target_entity_name)\n"
    "(source_entity_name)-[relationship_name: relationship_description]->"
    "(target_entity_name)\n"
    "(source_entity_name)-[relationship_name: relationship_property_map]->"
    "(target_entity_name)\n"
    "(chunk_id)-[Contains]->(entity_name)\n"
    "(catalog_id)-[Contains]->(chunk_id)\n"
    "(catalog_id)-[Contains]->(sub_catalog_id)\n"
    "(document_id)-[Contains]->(chunk_id)\n"
    "(document_id)-[Contains]->(catalog_id)\n"
    "\n"
    "### Skill 3: Graph Structure Understanding\n"
    "--Follow these steps to understand the graph structure--\n"
    "1. Correctly associate the source entity name in the "
    "relationship information with the entity information.\n"
    "2. Correctly associate the target entity name in the "
    "relationship information with the entity information.\n"
    "3. Reconstruct the graph structure based on the provided "
    "relationship information."
    "\n"
    "### Skill 4: Knowledge Graph Summarization\n"
    "--Follow these steps to summarize the knowledge graph--\n"
    "1. Determine the theme or topic expressed by the knowledge graph, "
    "highlighting key entities and relationships."
    "2. Use accurate, appropriate, and concise language to summarize "
    "the information expressed by the graph "
    "without generating irrelevant information."
    "\n"
    "## Constraints\n"
    "- Don't describe your thought process in the answer, provide the answer "
    "to the user's question directly without generating irrelevant information."
    "- Ensure the summary is written in the third person and objectively "
    "reflects the information conveyed by the knowledge graph.\n"
    "- If the descriptions of entities or relationships are empty and "
    "contribute nothing to the final summary, "
    "do not generate unrelated information.\n"
    "- If the provided descriptions are contradictory, resolve the conflicts "
    "and provide a single, coherent description.\n"
    "- Avoid using stop words and overly common words.\n"
    "\n"
    "## Reference Example\n"
    "--The case is only to help you understand the input and output format of "
    "the prompt, please do not use it in your answer.--\n"
    "Input:\n"
    "```\n"
    "Entities:\n"
    "(Phil Jaber#Founder of Philz Coffee)\n"
    "(Philz Coffee#Coffee brand founded in Berkeley, California)\n"
    "(Jacob Jaber#Son of Phil Jaber)\n"
    "(Multiple locations in the USA#Expansion regions of Philz Coffee)\n"
    "\n"
    "Relationships:\n"
    "(Phil Jaber#Created#Philz Coffee"
    "#Founded in Berkeley, California in 1978)\n"
    "(Philz Coffee#Located in#Berkeley, California"
    "#Founding location of Philz Coffee)\n"
    "(Phil Jaber#Has#Jacob Jaber#Son of Phil Jaber)\n"
    "(Jacob Jaber#Serves as#CEO#Became CEO of Philz Coffee in 2005)\n"
    "(Philz Coffee#Expanded to#Multiple locations in the USA"
    "#Expansion regions of Philz Coffee)\n"
    "```\n"
    "\n"
    "Output:\n"
    "```\n"
    "Philz Coffee is a coffee brand founded by Phil Jaber in 1978 in "
    "Berkeley, California. Phil Jaber's son, Jacob Jaber, took over as CEO in "
    "2005, leading the company to expand to multiple locations in the USA, "
    "further solidifying Philz Coffee's market position as a coffee brand "
    "founded in Berkeley, California.\n"
    "```\n"
    "\n"
    "----\n"
    "\n"
    "Please summarize the information expressed by the [KnowledgeGraph] "
    "provided in the following section according to the above requirements.\n"
    "\n"
    "[KnowledgeGraph]:\n"
    "{graph}\n"
    "\n"
    "[Summary]:\n"
    "\n"
)
